name: CI for egg interpreter

on: # when this action should be triggered?
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: # jobs are made of steps
  build:
    # Define the OS our workflow should run on
    runs-on: ${{ matrix.os }}

    strategy:
      # To test across multiple language versions
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, macos-latest]
 
 
    steps: # Clone the repo. See https://github.com/actions/checkout
    - uses: actions/checkout@v2
    - name: Setup npmrc
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc && echo "@ull-esit-pl-2122:registry=https://npm.pkg.github.com/" >> .npmrc

    # Example of using an environment variable
    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v1 # Install node. See https://github.com/actions/setup-node
      with:
        node-version: ${{ matrix.node-version }}
    # Install a project with a clean slate
    - run: npm i
    - run: npm test
      # Environment variables
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}